Slides session 1
rstudio-conf-2022/build-tidy-tools pull request #60
Opened 2022-07-13 18:00 UTC by beatrizmilz

Hi @3mmaRand ! 
Here are some small suggestions I made while reading the slides.
Fell free to tell me what suggestions do you want me to keep or remove from the PR, so I can adapt it!
Each commit message talks about why I'm making the suggestion.

Thanks!!

Ps:
This slide seems with no content except the title (but the slide before also had the title, so maybe you thought about adding something here?):

https://rstudio-conf-2022.github.io/build-tidy-tools/materials/day-1-session-1-introduction.html#/why-make-a-package-1

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/42153618/178799599-30afbdb1-4425-4e0e-a895-08bdd88bf134.png">

2022-07-15 08:37 UTC, 3mmaRand approved these changes
great, thanks

2022-07-15 08:40 UTC, 3mmaRand requested changes
Please could you remove this one @beatrizmilz 
You may need to resize you wondow but it should fit and I want consistency with the other slides

2022-07-15 08:41 UTC, 3mmaRand approved these changes
great, thanks you

2022-07-15 08:42 UTC, 3mmaRand approved these changes

2022-07-15 12:32 UTC, beatrizmilz commented on materials/day-1-session-1-introduction.qmd
> -    -   it will help you work more reproducibly
I did not knew that! :O thanks! I thought that was a typo!

2022-07-15 12:38 UTC, beatrizmilz commented
> Please could you remove this one @beatrizmilz You may need to resize you wondow but it should fit and I want consistency with the other slides

Emma, GitHub is not showing what this change is about! Is the changes in "# Where packages come from and live?"? thanks!

2022-07-16 09:24 UTC, merged

2022-07-16 09:26 UTC, 3mmaRand commented
> Emma, GitHub is not showing what this change is about! Is the changes in "# Where packages come from and live?"? thanks!

Sorted, don't worry. it was one of the package states slides. Sorry I didn't mark properly